### ISSUE TITLE
#US03 Publicar items para intercambiar

### ISSUE THREAD

**Issue by emaExeB1** [Paulac23/truwebque#2]
Como usuario quiero publicar items/productos para poder intercambiarlos

- [ ] crear el boton "cargar producto" (input file) dentro de la pagina Publicaciones
- [ ] generar formulario que solicite descripcion del producto:

- nombre del producto
- cantidad
- dimensiones
- estado del producto
- descripcion general

- [ ] crear boton "subir producto"

**Comment by agusval** [comment]
El formulario puede tener varias descripciones. Al momento se me ocurrieron esas
