### ISSUE TITLE
#US10 Filtrar publicaciones por categorías

### ISSUE THREAD

**Issue by gonzalom90** [Paulac23/truwebque#3]
# FILTROS

### Problema a solucionar

Se pretende filtrar por categoría *los productos que se encuentren disponibles para el intercambio*.

### Tareas

- [ ] Elegir las __categorías__. 📚 
- [ ] Crear **consulta** en base de datos. 🔍 
- [ ] Agregar opción de filtro en la página principal mediante __"CheckBox"__. ✅

**Comment by gonzalom90** [comment]
Que categorías te parece que agreguemos @Roberto-Osores ? Yo pensaba: Librería, Informática, Antigüedades, Música, Deportes...

**Comment by Roberto-Osores** [comment]
Quizás estaría bueno usar Categorías mas amplias como lo hace ML; por ejemplo en lugar de "Música"=>"Música, Películas y Series".
Usar  etiquetas que ya usan otras plataformas viene con el beneficio que los posibles usuarios finales de nuestra web ya las conocen y les van a resultar mas intuitivas. Dejo una lista tentativa extraída de [https://www.mercadolibre.com.ar/categorias#menu=categories](url) :

- Accesorios para Vehículos
- Agro
- Alimentos y Bebidas
- Animales y Mascotas
- Antigüedades y Colecciones
- Arte, Librería y Mercería
- Autos, Motos y Otros
- Bebés (Artículos para bebes, no bebes ja)
- Belleza y Cuidado Personal
- Cámaras y Accesorios
- Celulares y Teléfonos
- Computación
- Consolas y Videojuegos
- Construcción
- Deportes y Fitness
- Electrodomésticos y Aires Ac.
- Electrónica, Audio y Video
- Entradas para Eventos
- Herramientas
- Hogar, Muebles y Jardín
- Industrias y Oficinas
- Inmuebles
- Instrumentos Musicales
- Joyas y Relojes
- Juegos y Juguetes
- Libros, Revistas y Comics
- Música, Películas y Series
- Ropa y Accesorios
- Salud y Equipamiento Médico
- Servicios
- Souvenirs, Cotillón y Fiestas
- Otras categorías
